//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensur.Core.Utilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ensur.Core.Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user account is locked in ENSUR.
        /// </summary>
        public static string ACCOUNT_LOCKED {
            get {
                return ResourceManager.GetString("ACCOUNT_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected by Active Directory.
        /// </summary>
        public static string AD_REJECT {
            get {
                return ResourceManager.GetString("AD_REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account is presently logged into ENSUR, but multiple logins are disallowed.
        /// </summary>
        public static string ALREADY_LOGGEDIN {
            get {
                return ResourceManager.GetString("ALREADY_LOGGEDIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user must have an editor role to use the API.
        /// </summary>
        public static string API_EDITOR {
            get {
                return ResourceManager.GetString("API_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All available user seats are taken.  Please wait for one of the other users to finish or expand the number of licenses available.
        /// </summary>
        public static string API_LICENSE_FULL {
            get {
                return ResourceManager.GetString("API_LICENSE_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid site.  You must have a Site created in Ensur with the name ENSURAPI and a valid license key..
        /// </summary>
        public static string API_NO_VALID_SITE {
            get {
                return ResourceManager.GetString("API_NO_VALID_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing required attributes.  Please check the list of required attributes and submit values for each..
        /// </summary>
        public static string ATTRIBUTE_MISSING_REQUIRED {
            get {
                return ResourceManager.GetString("ATTRIBUTE_MISSING_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attribute of the specified type and ID was not found on this document.
        /// </summary>
        public static string ATTRIBUTE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ATTRIBUTE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified component is part of a grid and can&apos;t be returned in this call.  See the /Forms/{ID}/Grid call and the API documentation for further details..
        /// </summary>
        public static string COMPONENT_GRID {
            get {
                return ResourceManager.GetString("COMPONENT_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid component name or ID.  Please make sure you have the correct combination of content ID and either component name or ID..
        /// </summary>
        public static string COMPONENT_ID_OR_NAME {
            get {
                return ResourceManager.GetString("COMPONENT_ID_OR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified component is not currently supported or does not allow saving.  Please exclude this from your data..
        /// </summary>
        public static string COMPONENT_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("COMPONENT_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component is read only.  Saving is not allowed..
        /// </summary>
        public static string COMPONENT_READ_ONLY {
            get {
                return ResourceManager.GetString("COMPONENT_READ_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component is read only because it is linked to a master.  Saving is not allowed..
        /// </summary>
        public static string COMPONENT_READ_ONLY_MASTER {
            get {
                return ResourceManager.GetString("COMPONENT_READ_ONLY_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type does not exist.  Please check the content type name or ID and try again..
        /// </summary>
        public static string CONTENT_TYPE_NONEXISTANT {
            get {
                return ResourceManager.GetString("CONTENT_TYPE_NONEXISTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conversion resulted in a value ({VAL}) that was outside of the range of values ({RANGE})..
        /// </summary>
        public static string CONVERSION_ERROR_RANGE {
            get {
                return ResourceManager.GetString("CONVERSION_ERROR_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid overlay.  To use an overlay with the API there must be a controlled print overlay configured..
        /// </summary>
        public static string DOC_INVALID_OVERLAY {
            get {
                return ResourceManager.GetString("DOC_INVALID_OVERLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document is already checked out by {USER}.  Please either contact them or undo the checkout before proceeding..
        /// </summary>
        public static string DOCUMENT_ALREADY_LOCKED {
            get {
                return ResourceManager.GetString("DOCUMENT_ALREADY_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure to include values for ALL required attributes in your request..
        /// </summary>
        public static string DOCUMENT_ATTRIBUTES_REQ {
            get {
                return ResourceManager.GetString("DOCUMENT_ATTRIBUTES_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document is already checked out by {USER}.  Please either contact them or undo the checkout before proceeding..
        /// </summary>
        public static string DOCUMENT_CHECKED_OUT {
            get {
                return ResourceManager.GetString("DOCUMENT_CHECKED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in notes are required for this document type..
        /// </summary>
        public static string DOCUMENT_CHECKIN_NOTES {
            get {
                return ResourceManager.GetString("DOCUMENT_CHECKIN_NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document is not in a status that is eligible for checkout..
        /// </summary>
        public static string DOCUMENT_CHECKOUT_STATUS {
            get {
                return ResourceManager.GetString("DOCUMENT_CHECKOUT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not check out the form. User not in Co-Editors list..
        /// </summary>
        public static string DOCUMENT_CO_EDITOR {
            get {
                return ResourceManager.GetString("DOCUMENT_CO_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code already exists, each Code must be unique.
        /// </summary>
        public static string DOCUMENT_CODE_EXISTS {
            get {
                return ResourceManager.GetString("DOCUMENT_CODE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document must be in draft status..
        /// </summary>
        public static string DOCUMENT_DRAFT_STATUS {
            get {
                return ResourceManager.GetString("DOCUMENT_DRAFT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content record prohibits checkouts for this review cycle..
        /// </summary>
        public static string DOCUMENT_EDIT_REVIEW {
            get {
                return ResourceManager.GetString("DOCUMENT_EDIT_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content deleted from folder {FolderName}.
        /// </summary>
        public static string DOCUMENT_FOLDER_REMOVE {
            get {
                return ResourceManager.GetString("DOCUMENT_FOLDER_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document must be in format {FORMAT} to complete this operation..
        /// </summary>
        public static string DOCUMENT_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("DOCUMENT_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot link to obselete content.  Must be in Current or earlier status..
        /// </summary>
        public static string DOCUMENT_INVALID_LINK {
            get {
                return ResourceManager.GetString("DOCUMENT_INVALID_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document is in a status that does not allow this action.  .
        /// </summary>
        public static string DOCUMENT_INVALID_STATUS {
            get {
                return ResourceManager.GetString("DOCUMENT_INVALID_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing the view rights for document code {CODE}.
        /// </summary>
        public static string DOCUMENT_MISSING_VIEW_RIGHTS {
            get {
                return ResourceManager.GetString("DOCUMENT_MISSING_VIEW_RIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document must be checked out.
        /// </summary>
        public static string DOCUMENT_MUST_CHECKEDOUT {
            get {
                return ResourceManager.GetString("DOCUMENT_MUST_CHECKEDOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content file is not available in its current status..
        /// </summary>
        public static string DOCUMENT_NO_FILE {
            get {
                return ResourceManager.GetString("DOCUMENT_NO_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no eligible reviewer options on the review routing..
        /// </summary>
        public static string DOCUMENT_NO_REVIEWERS {
            get {
                return ResourceManager.GetString("DOCUMENT_NO_REVIEWERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitters are not allowed to checkout content that they have submitted for review per system configuration..
        /// </summary>
        public static string DOCUMENT_NO_SUB_CHECKOUT {
            get {
                return ResourceManager.GetString("DOCUMENT_NO_SUB_CHECKOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a document with the ID of {ID}.  Please check your ID and try again..
        /// </summary>
        public static string DOCUMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("DOCUMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product type, you can only lock Documents.
        /// </summary>
        public static string DOCUMENT_ONLY_LOCK {
            get {
                return ResourceManager.GetString("DOCUMENT_ONLY_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This overlay has required prompts that must be provided.  For more details check the /document/{ID}/Prompts endpoint..
        /// </summary>
        public static string DOCUMENT_OVERLAY_PROMPTS {
            get {
                return ResourceManager.GetString("DOCUMENT_OVERLAY_PROMPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The overlay for this document has no prompt with this ID.  Please re-check the IDs you are passing.  (Note: Entry IDs change when an overlay is revised).
        /// </summary>
        public static string DOCUMENT_PROMPT_INVALID {
            get {
                return ResourceManager.GetString("DOCUMENT_PROMPT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content type for this document does not allow the revision to be adjusted..
        /// </summary>
        public static string DOCUMENT_REV_NOT_ADJUSTABLE {
            get {
                return ResourceManager.GetString("DOCUMENT_REV_NOT_ADJUSTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid status for lock.  Must be in Approved or Current status..
        /// </summary>
        public static string DOCUMENT_STATUS_LOCK {
            get {
                return ResourceManager.GetString("DOCUMENT_STATUS_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be less than {MaxLength} characters..
        /// </summary>
        public static string FIELD_LENGTH {
            get {
                return ResourceManager.GetString("FIELD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be in the list of acceptable values.  Please see the documentation for further details..
        /// </summary>
        public static string FIELD_LIST {
            get {
                return ResourceManager.GetString("FIELD_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string FIELD_REQUIRED {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem creating the following file/folder {PATH}.
        /// </summary>
        public static string FILE_CREATE_ERROR {
            get {
                return ResourceManager.GetString("FILE_CREATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem deleting the following file/folder {PATH}.
        /// </summary>
        public static string FILE_DELETE_ERROR {
            get {
                return ResourceManager.GetString("FILE_DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File MIME/Content type does not match extension MIME/Content type.  Please check that the file you are uploading is in the correct format and named properly..
        /// </summary>
        public static string FILE_MIME_INCORRECT {
            get {
                return ResourceManager.GetString("FILE_MIME_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document has an overlay and all published content must be in PDF format..
        /// </summary>
        public static string FILE_MUST_PDF {
            get {
                return ResourceManager.GetString("FILE_MUST_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you are looking for could not be found.  Please contact your administrator and try again..
        /// </summary>
        public static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was included with your request.  Please check your request and try again..
        /// </summary>
        public static string FILE_NOT_PROVIDED {
            get {
                return ResourceManager.GetString("FILE_NOT_PROVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type of file is not allowed.  Please contact your system administrator for more information..
        /// </summary>
        public static string FILE_TYPE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("FILE_TYPE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have access to this folder and all sub-folders in order to delete.
        /// </summary>
        public static string FOLDER_DELETE_ACCESS {
            get {
                return ResourceManager.GetString("FOLDER_DELETE_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete a folder that contains documents.
        /// </summary>
        public static string FOLDER_DELETE_EMPTY {
            get {
                return ResourceManager.GetString("FOLDER_DELETE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete the root folder.
        /// </summary>
        public static string FOLDER_DELETE_ROOT {
            get {
                return ResourceManager.GetString("FOLDER_DELETE_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the subfolders has the same name as a sibling folder.  Rename that folder before deleting..
        /// </summary>
        public static string FOLDER_DELETE_SAMENAME {
            get {
                return ResourceManager.GetString("FOLDER_DELETE_SAMENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not allow this type of product.  Please specify a different folder..
        /// </summary>
        public static string FOLDER_PRODUCT_TYPE {
            get {
                return ResourceManager.GetString("FOLDER_PRODUCT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form type must match this document&apos;s product type.
        /// </summary>
        public static string FORM_TYPE_MATCH {
            get {
                return ResourceManager.GetString("FORM_TYPE_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula is invalid and not able to be evaluated. .
        /// </summary>
        public static string FRM_FORMULA_INVALID {
            get {
                return ResourceManager.GetString("FRM_FORMULA_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error performing your request.  Please try again later..
        /// </summary>
        public static string GENERAL_ERROR {
            get {
                return ResourceManager.GetString("GENERAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create hyperlink is not currently enabled.  Please contact your Ensur administrator to enable it..
        /// </summary>
        public static string HYPERLINK_NOT_ENABLED {
            get {
                return ResourceManager.GetString("HYPERLINK_NOT_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change was made by user {UserID} impersonating user {ImpersonationID}.
        /// </summary>
        public static string IMPERSONATION {
            get {
                return ResourceManager.GetString("IMPERSONATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be an Owner of this Incident.
        /// </summary>
        public static string INCIDENT_OWNER_CHECKOUT {
            get {
                return ResourceManager.GetString("INCIDENT_OWNER_CHECKOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your value has invalid characters.  {CHARACTERS} Please check your value and try again..
        /// </summary>
        public static string INVALID_CHARACTERS {
            get {
                return ResourceManager.GetString("INVALID_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find all or part of the folder path.  Please check the path and try again..
        /// </summary>
        public static string INVALID_FOLDER_PATH {
            get {
                return ResourceManager.GetString("INVALID_FOLDER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your valid is not in the expected format.  Expected format is  {EXPECTED_FORMAT}.
        /// </summary>
        public static string INVALID_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The media you specified does not have a file associated with it.  (Link or Web URL).
        /// </summary>
        public static string INVALID_MEDIA {
            get {
                return ResourceManager.GetString("INVALID_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value is invalid.  It must contain the following character(s) {CHARACTERS}.
        /// </summary>
        public static string INVALID_MUST_CONTAIN {
            get {
                return ResourceManager.GetString("INVALID_MUST_CONTAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ENSUR password.
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have specified an invalid value for this field..
        /// </summary>
        public static string INVALID_VALUE {
            get {
                return ResourceManager.GetString("INVALID_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have specified an invalid value for this field.  Expecting type {TYPE}..
        /// </summary>
        public static string INVALID_VALUE_TYPE {
            get {
                return ResourceManager.GetString("INVALID_VALUE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the specified key.  Please check your ID and try again..
        /// </summary>
        public static string KEY_NOT_FOUND {
            get {
                return ResourceManager.GetString("KEY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license has expired.  Please contact Ensur support at support@docxellent.com.
        /// </summary>
        public static string LICENSE_EXPIRED {
            get {
                return ResourceManager.GetString("LICENSE_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, child already linked to a CO.
        /// </summary>
        public static string LINK_CHILD_CO {
            get {
                return ResourceManager.GetString("LINK_CHILD_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, Child cannot be added until all DEP-STAT parents are members of the CO.
        /// </summary>
        public static string LINK_CHILD_DEP_STAT {
            get {
                return ResourceManager.GetString("LINK_CHILD_DEP_STAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action would create a circular reference..
        /// </summary>
        public static string LINK_CIRCULAR_REFERENCE {
            get {
                return ResourceManager.GetString("LINK_CIRCULAR_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To delete a change order link beyond In-Review status, the CO must be in Approved status and locked..
        /// </summary>
        public static string LINK_CO_DELETE {
            get {
                return ResourceManager.GetString("LINK_CO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, you cannot link a CO to another CO.
        /// </summary>
        public static string LINK_CO_TO_CO {
            get {
                return ResourceManager.GetString("LINK_CO_TO_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code already linked to parent document.
        /// </summary>
        public static string LINK_CODE_EXISTS {
            get {
                return ResourceManager.GetString("LINK_CODE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete an active dependent link.
        /// </summary>
        public static string LINK_DELETE_ACTIVE {
            get {
                return ResourceManager.GetString("LINK_DELETE_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, Child cannot be added until all DEP-DYNAMIC parents that are not yet Current are represented in the CO.
        /// </summary>
        public static string LINK_DEP_DYNAMIC_NOT_CURRENT {
            get {
                return ResourceManager.GetString("LINK_DEP_DYNAMIC_NOT_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To delete a dependent link, you must checkout the Parent document..
        /// </summary>
        public static string LINK_DOCUMENT_CHECKOUT {
            get {
                return ResourceManager.GetString("LINK_DOCUMENT_CHECKOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A link between these documents already exists.
        /// </summary>
        public static string LINK_EXISTS {
            get {
                return ResourceManager.GetString("LINK_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masters require parent and child to both be forms..
        /// </summary>
        public static string LINK_MASTER_FORM {
            get {
                return ResourceManager.GetString("LINK_MASTER_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document must be in {STATUS} status..
        /// </summary>
        public static string LINK_MUST_BE_STATUS {
            get {
                return ResourceManager.GetString("LINK_MUST_BE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, child cannot be obsolete.
        /// </summary>
        public static string LINK_OBSELETE {
            get {
                return ResourceManager.GetString("LINK_OBSELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent and child documents must be of the same Product Type.
        /// </summary>
        public static string LINK_TEMPLATE_PRODUCT {
            get {
                return ResourceManager.GetString("LINK_TEMPLATE_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded number of invalid login attempts.
        /// </summary>
        public static string MAX_LOGIN_TRIES {
            get {
                return ResourceManager.GetString("MAX_LOGIN_TRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the required rights to access this folder.  Please contact your system administrator for assistance..
        /// </summary>
        public static string MISSING_FOLDER_RIGHTS {
            get {
                return ResourceManager.GetString("MISSING_FOLDER_RIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the required rights to perform this action.  Please contact your system administrator for assistance. .
        /// </summary>
        public static string MISSING_RIGHTS {
            get {
                return ResourceManager.GetString("MISSING_RIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a multi-value component, please use the multi-value field..
        /// </summary>
        public static string MULTI_VALUE_COMPONENT {
            get {
                return ResourceManager.GetString("MULTI_VALUE_COMPONENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to view this content, but you do not have proper access to this document in the Ensur system. Please contact your System Administrator for assistance..
        /// </summary>
        public static string NO_ACCESS {
            get {
                return ResourceManager.GetString("NO_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no licenses available to use.  Please contact your administrator to be put on an appropriate license..
        /// </summary>
        public static string NO_AVAILABLE_LICENSE {
            get {
                return ResourceManager.GetString("NO_AVAILABLE_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to view this content, but no original or publish content has been loaded. Please import content and try your request again..
        /// </summary>
        public static string NO_CONTENT {
            get {
                return ResourceManager.GetString("NO_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System logins are not allowed at this time (system is offline).
        /// </summary>
        public static string NO_LOGINS {
            get {
                return ResourceManager.GetString("NO_LOGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Original Content. You are attempting to view original content, but no such content has been loaded.  Please import original content and try your request again..
        /// </summary>
        public static string NO_ORIGINAL_CONTENT {
            get {
                return ResourceManager.GetString("NO_ORIGINAL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to view Published content, but it must be a PDF in order to apply the overlay. Please refresh your browser, import published PDF content and try your request again..
        /// </summary>
        public static string NO_PDF {
            get {
                return ResourceManager.GetString("NO_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Published Content.  You are attempting to view published content , but no such content has been loaded.  Please import published content and try again..
        /// </summary>
        public static string NO_PUBLISHED_CONTENT {
            get {
                return ResourceManager.GetString("NO_PUBLISHED_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repository set! .
        /// </summary>
        public static string NO_REPOSITORY {
            get {
                return ResourceManager.GetString("NO_REPOSITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field does not allow saving..
        /// </summary>
        public static string NO_SAVING_ALLOWED {
            get {
                return ResourceManager.GetString("NO_SAVING_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading files are not allowed to this document..
        /// </summary>
        public static string NO_UPLOAD {
            get {
                return ResourceManager.GetString("NO_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User authentication failed: The provided username is not associated with the provided domain in ENSUR..
        /// </summary>
        public static string NO_USER_OR_DOMAIN {
            get {
                return ResourceManager.GetString("NO_USER_OR_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided account for the provided username is not active in ENSUR.
        /// </summary>
        public static string NOT_ACTIVE {
            get {
                return ResourceManager.GetString("NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this operation.  Please talk to your system administrator for more information..
        /// </summary>
        public static string NOT_AUTHORIZED {
            get {
                return ResourceManager.GetString("NOT_AUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value is currently unsupported.  Please review the documentation and change the value..
        /// </summary>
        public static string NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification is inactive.
        /// </summary>
        public static string NOTFIFY_NOTIFY_INACTIVE {
            get {
                return ResourceManager.GetString("NOTFIFY_NOTIFY_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Description: {DESCRIPTION}.
        /// </summary>
        public static string NOTIFY_AI_DESC {
            get {
                return ResourceManager.GetString("NOTIFY_AI_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing as an Action Item Notification.
        /// </summary>
        public static string NOTIFY_AI_NOTE {
            get {
                return ResourceManager.GetString("NOTIFY_AI_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Date Driven: {DATE_DRIVEN}.
        /// </summary>
        public static string NOTIFY_DATE_DRIVEN {
            get {
                return ResourceManager.GetString("NOTIFY_DATE_DRIVEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing as a Document Notification..
        /// </summary>
        public static string NOTIFY_DOC_NOTE {
            get {
                return ResourceManager.GetString("NOTIFY_DOC_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is inactive..
        /// </summary>
        public static string NOTIFY_EMAIL_INACTIVE {
            get {
                return ResourceManager.GetString("NOTIFY_EMAIL_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {USERCOUNT} users.
        /// </summary>
        public static string NOTIFY_FOUND_USERS {
            get {
                return ResourceManager.GetString("NOTIFY_FOUND_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using HTML Body.
        /// </summary>
        public static string NOTIFY_HTML_BODY {
            get {
                return ResourceManager.GetString("NOTIFY_HTML_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing notification:  {EVENT_ID} {DESCRIPTION}.
        /// </summary>
        public static string NOTIFY_PROCESSING {
            get {
                return ResourceManager.GetString("NOTIFY_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing as a routing notification.
        /// </summary>
        public static string NOTIFY_ROUTING_NOTE {
            get {
                return ResourceManager.GetString("NOTIFY_ROUTING_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing as a session notification.
        /// </summary>
        public static string NOTIFY_SESSION_NOTIFY {
            get {
                return ResourceManager.GetString("NOTIFY_SESSION_NOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Plain Text Body.
        /// </summary>
        public static string NOTIFY_TEXT_BODY {
            get {
                return ResourceManager.GetString("NOTIFY_TEXT_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification type: {NTYPE}.
        /// </summary>
        public static string NOTIFY_TYPE {
            get {
                return ResourceManager.GetString("NOTIFY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing as a user notification.
        /// </summary>
        public static string NOTIFY_USER_NOTE {
            get {
                return ResourceManager.GetString("NOTIFY_USER_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the original file can be downloaded.
        /// </summary>
        public static string ORIGINAL_ONLY {
            get {
                return ResourceManager.GetString("ORIGINAL_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has expired.
        /// </summary>
        public static string PASSWORD_EXPIRED {
            get {
                return ResourceManager.GetString("PASSWORD_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a system picklist and cannot be modified or deleted..
        /// </summary>
        public static string PICKLIST_SYSTEM {
            get {
                return ResourceManager.GetString("PICKLIST_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the published file can be downloaded.
        /// </summary>
        public static string PUBLISHED_ONLY {
            get {
                return ResourceManager.GetString("PUBLISHED_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin password is configured to not be changable..
        /// </summary>
        public static string PW_ADMIN_PREVENT {
            get {
                return ResourceManager.GetString("PW_ADMIN_PREVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password is on the disallowed password list.  Please pick another password..
        /// </summary>
        public static string PW_DISALLOWED {
            get {
                return ResourceManager.GetString("PW_DISALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lower case character.
        /// </summary>
        public static string PW_LOWER {
            get {
                return ResourceManager.GetString("PW_LOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {LENGTH} characters long.
        /// </summary>
        public static string PW_MIN_LENGTH {
            get {
                return ResourceManager.GetString("PW_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number.
        /// </summary>
        public static string PW_NUMBER {
            get {
                return ResourceManager.GetString("PW_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character.
        /// </summary>
        public static string PW_SPECIAL {
            get {
                return ResourceManager.GetString("PW_SPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one upper case character.
        /// </summary>
        public static string PW_UPPER {
            get {
                return ResourceManager.GetString("PW_UPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result exceeded the maximum value of {MAX} digits..
        /// </summary>
        public static string RESULT_EXCEEDED_MAX {
            get {
                return ResourceManager.GetString("RESULT_EXCEEDED_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This row cannot be deleted because it is linked to a master row..
        /// </summary>
        public static string ROW_DELETE_MASTER {
            get {
                return ResourceManager.GetString("ROW_DELETE_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This paramater accepts the following values {VALUES}.
        /// </summary>
        public static string SERIALIZATION_ENUM {
            get {
                return ResourceManager.GetString("SERIALIZATION_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error parsing the value for parameter {PARAMETER}.  Please check your JSON structure and values.  Make sure text (strings) or dates are surrounded by quotes and numbers or booleans are not.  {MESSAGE}.
        /// </summary>
        public static string SERIALIZATION_ERROR {
            get {
                return ResourceManager.GetString("SERIALIZATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a single-value component, please use the single-value field..
        /// </summary>
        public static string SINGLE_VALUE_COMPONENT {
            get {
                return ResourceManager.GetString("SINGLE_VALUE_COMPONENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is required.
        /// </summary>
        public static string SPECIFIC_FIELD_REQUIRED {
            get {
                return ResourceManager.GetString("SPECIFIC_FIELD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content type you have chosen is not supported.  Only Windows Application / Form based content types are allowed..
        /// </summary>
        public static string TEMP_CONTENT_TYPE {
            get {
                return ResourceManager.GetString("TEMP_CONTENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a published file can be added to this document..
        /// </summary>
        public static string UPLOAD_ONLY_PUBLISHED {
            get {
                return ResourceManager.GetString("UPLOAD_ONLY_PUBLISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include a single file with your request..
        /// </summary>
        public static string UPLOAD_SINGLE_FILE {
            get {
                return ResourceManager.GetString("UPLOAD_SINGLE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following users are not active supervisors in the system : {users}.
        /// </summary>
        public static string USER_SUBS_INVALID {
            get {
                return ResourceManager.GetString("USER_SUBS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User must be a supervisor to have subordinates.
        /// </summary>
        public static string USER_SUPER_SUB {
            get {
                return ResourceManager.GetString("USER_SUPER_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When local authentication is set, you must choose the Ensur domain..
        /// </summary>
        public static string VAL_LOCAL_DOMAIN {
            get {
                return ResourceManager.GetString("VAL_LOCAL_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must use local authentication when setting your own passwords..
        /// </summary>
        public static string VAL_LOCAL_PW {
            get {
                return ResourceManager.GetString("VAL_LOCAL_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a boolean (true/false).
        /// </summary>
        public static string VALUE_BOOL_ONLY {
            get {
                return ResourceManager.GetString("VALUE_BOOL_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be set to a valid Date/Time value.  .
        /// </summary>
        public static string VALUE_DATETIME_INVALID {
            get {
                return ResourceManager.GetString("VALUE_DATETIME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .
        /// </summary>
        public static string VALUE_ENG_MET {
            get {
                return ResourceManager.GetString("VALUE_ENG_MET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is not set to a valid integer value.  Please correct your data and try again..
        /// </summary>
        public static string VALUE_INT_INVALID {
            get {
                return ResourceManager.GetString("VALUE_INT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All co-owners must be Active, be an Approver or Editor, and must have Content-Owner rights to the destination folder.  The following user(s) are invalid {USERS}..
        /// </summary>
        public static string VALUE_INVALID_COOWNERS {
            get {
                return ResourceManager.GetString("VALUE_INVALID_COOWNERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must include the value property in your JSON structure. If you are setting a null value, include the value property with a value of null..
        /// </summary>
        public static string VALUE_JSON {
            get {
                return ResourceManager.GetString("VALUE_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value allows letters only (No spaces, punctuation or numbers).
        /// </summary>
        public static string VALUE_LETTERS_ONLY {
            get {
                return ResourceManager.GetString("VALUE_LETTERS_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can&apos;t have more than {MAX} characters.
        /// </summary>
        public static string VALUE_MAX_CHAR {
            get {
                return ResourceManager.GetString("VALUE_MAX_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must have at least {MIN} characters.
        /// </summary>
        public static string VALUE_MIN_CHAR {
            get {
                return ResourceManager.GetString("VALUE_MIN_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a decimal (numbers and a decimal place only).
        /// </summary>
        public static string VALUE_NUM_DECIMAL {
            get {
                return ResourceManager.GetString("VALUE_NUM_DECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be smaller than or equal to {MAX}  .
        /// </summary>
        public static string VALUE_NUM_E_MAX {
            get {
                return ResourceManager.GetString("VALUE_NUM_E_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be equal to or larger than {MIN}.
        /// </summary>
        public static string VALUE_NUM_E_MIN {
            get {
                return ResourceManager.GetString("VALUE_NUM_E_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be an integer (numbers only, no decimals).
        /// </summary>
        public static string VALUE_NUM_INT {
            get {
                return ResourceManager.GetString("VALUE_NUM_INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be smaller than {MAX}.
        /// </summary>
        public static string VALUE_NUM_MAX {
            get {
                return ResourceManager.GetString("VALUE_NUM_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be larger than {MIN}.
        /// </summary>
        public static string VALUE_NUM_MIN {
            get {
                return ResourceManager.GetString("VALUE_NUM_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is not set to an valid option.  Please correct your data and try again..
        /// </summary>
        public static string VALUE_OPTION_INVALID {
            get {
                return ResourceManager.GetString("VALUE_OPTION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result exceeded the max length of {MAX} characters.  .
        /// </summary>
        public static string VALUE_RESULT_MAX {
            get {
                return ResourceManager.GetString("VALUE_RESULT_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must include the values property in your JSON structure. If you are setting a null value, include the values property with an empty array..
        /// </summary>
        public static string VALUES_JSON {
            get {
                return ResourceManager.GetString("VALUES_JSON", resourceCulture);
            }
        }
    }
}
